import 'package:bookit_user_app/widgets/appbar_widget.dart';
import 'package:bookit_user_app/widgets/drawer_widget.dart';
import 'package:flutter/material.dart';

class TermsAndConditionsScreen extends StatelessWidget {
  const TermsAndConditionsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppbarWidget(title: 'Terms and Conditions'),
        drawer: DrawerWidget(),
        body: buildTermsAndConditions());
  }

  buildTermsAndConditions() {
    return Padding(
      padding: const EdgeInsets.all(15),
      child: ListView(
        children: [
          Text(
            'Ganishga Bookit  Private limited Terms and Conditions :',
            style: TextStyle(fontSize: 23, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 10),
          Text(
            '1.The following Terms & Conditions shall apply to customers / passengers utilising the Services offered by Bookit Cabs for the hiring of  Cabs.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            '2.This electronic  record is generated by a computer system and this document is an electronic record in terms of information  technology act, 2000 and rules thereunder as applicable and the  provisions pertaining to electronic records in various statutes as amended by the information technology Act, 2000 does not require any  physical or digital signatures.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            '3.By clicking on the “I Accept” button on this electronic contract, you are consenting to be bound by this  subscription agreement along with the various exhibits attached to  the subscription agreement. please ensure that you read and  understand all the provisions of this subscription agreement and  exhibits before you start using the portal, as you shall be bound by  all the terms herein upon clicking on the “Accept & Continue”  button on this electronic contract.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            '4.If you do not accept any of the Terms contained herein, then please do not use the portal or avail  any of the services being provided therein. Your agreement to the  subscription agreement shall operate as a binding agreement  between you and Ganishga Bookit Private  limited  in respect of the services of the portal.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Ganishga Bookit Pvt Ltd is only Aggregator :',
            style: TextStyle(fontSize: 23, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 10),
          Text(
            'The customer shall pay the  cab fare (as displayed in the meter), parking charges, additional night surcharge (where applicable) and any fee or levy presently payable or hereinafter imposed by the law or required to be paid for availing of the  Cab Services.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'The customer agrees and accepts that the use of the Services provided by the Bookit cabs is at the sole risk of the Customer, and further acknowledges that the Company disclaims all representations and warranties of any kind, whether express or implied.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'The customer shall ensure that he/she will not indulge in any of the following activities while in a Bookit Cabs.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'a) Smoking or consuming any kind of intoxicants inside the Cab. The Driver has the right to refuse the pick-up or ask the customer to alight the cab if the customer is found to be in an intoxicated state or is found misbehaving with other passengers or the Driver, or is causing a nuisance.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'b) Littering the Cab.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'c) Soiling or damaging the seats and/or any other interiors of the Cab.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'd) Misusing, soiling or damaging any of the devices  (technical/non-technical) in the Cab.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'e) Asking the Sat Driver to break any Traffic/RTO/ City Police and/or government rules for any purpose (especially reaching the destination earlier). The driver has the right to refuse such a request by the customer.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'f) Asking the Driver to board more than 4 adults in the (mini and sedan) Cab . The rules under which the Cab services are provided by the Company, stipulate that a maximum of 4 adult passengers shall be allowed per trip. In view of this, the customer shall not pressurize the Driver to allow more than 4 adult passengers in the Cab The Driver has the right to refuse such a pick-up.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'g) Pressurizing the Driver to overload the boot space of the Cab with luggage. The customer shall not be generally allowed to use the seating area of the Cab for placing any kind of luggage.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'The customer agrees and acknowledges that the use of the Services offered by Bookit Cabs is at the sole risk of the customer and that Bookit Cabs disclaims all representations and warranties of any kind, whether express or implied as to condition, suitability, quality, merchantability and fitness for any purposes are excluded to the fullest extent permitted by law.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'a) The Services will meet the customer\'s requirements.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'b) The Services will be uninterrupted, timely, secure, or error-free.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'c) Bookit Cabs shall not be responsible or liable for any loss or damage, howsoever caused or suffered by the Customer arising out of the use of Cab service offered by Bookit cabs or due to the failure of Bookit Cabs to provide Services to the Customer for any reason whatsoever including but not limited to the Customer\'s non-compliance with the Services recorded voice instructions, malfunction, partial or total failure of any network terminal, data processing system, computer tele-transmission or telecommunications system or other circumstances whether or not beyond the control of  Bookit Cabs or any person or any organization involved in the above mentioned systems.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'd) Cab will not be liable for any damages of any kind arising from the use of the service offered by bookit Cabs, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'e) There shall be extra charges for far off locations & toll charges as well.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'f) If any passenger misses the train or flight or bus, Bookit cabs will not be liable for any compensation. The customer shall make an alternate arrangement if the cab has not reached due to any reason.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'The Customer shall indemnify Bookit Cabs  from and against and in respect of any or all liabilities, losses, charges and expenses (including legal fees and costs on a full indemnity basis) claims, demands, actions and proceedings which Bookit cabs  may incur or sustain directly or indirectly from or by any reason of or in relation to the use or proposed use of the Services by the Customer and shall pay such sums on demand on Bookit Cabs.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit Cabs  is hereby authorized to use the location based information provided by any of the telecommunication companies when the Customer uses the mobile phone to make a Cab booking. The location based information will be used only to facilitate and improve the probability of locating a Cab for the Customer.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit Cabs  shall be entitled to disclose to all companies within its group, or any government body as so required by the law or by directive or request from any government body, the particulars of the Customer in the possession of Bookit Cabs in any way as Bookit Cabs, in its absolute discretion, deems fit or if it considers it in its interests to do so.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit Cabs shall be entitled at any time without giving any reason to terminate the booking of Cabs done by the Customer. ',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit cabs encourages all its customers to take full responsibility of his/her items. In case of lost items inside the Cab during the journey, Bookit Cabs will try to locate the items on a "best-effort" basis but is not responsible for the same in case of loss or damage to the same.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'If the Customer leaves any goods in the Cab or has any complaint in respect of the Services or the use of the Cab, the Customer has to inform Bookit Cabs of the same in writing within 24hours of using the Cab or the Services of Bookit Cabs.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit Cabs Shall not be liable for any conduct of the Driver of the Cabs. However, Bookit Cabs encourages you to notify it of any complaints that you may have against the Driver of any Cab that you may have hired using the Bookit Cabs Services.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit Cabs shall be entitled to add to, vary or amend any or all these terms and conditions at any time and the Customer shall be bound by such addition, variation or amendment.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'All the calls made to Bookit Cabs call centre are recorded by Bookit cabs for quality and training purposes.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit cabs have right to use the customer contact information for its own marketing purposes.Bookit Cabs may send regular SMS updates to the mobile numbers registered with it.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Online booking has to be cancelled by calling to our customer care number 8110811066. For online and real time booking, Cancellation charge of Rs.50, has to be paid for the booking cancelled, after the cab reached pickup place.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'The above mentioned terms and conditions of use and the Privacy Policy constitute the entire agreement between the User(s) and Bookit cabs with respect to access to and use of the web site and the Services offered by Bookit Cabs, superseding any prior written or oral agreements in relation to the same subject matter herein.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'By using the Mobile Application or the Service, You further agree that:',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You will only use the Service or download the Application for Your sole, personal use and will not resell or assign it to a third party.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You will not use an account that is subject to any rights of a person other than You without appropriate authorization.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You will not use the Service or Site for unlawful purposes.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You will not try to harm the Service, Site or our network in any way whatsoever.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You will provide Bookit Cabs with such information and documents which may reasonably request.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You will only use an authorized network to avail the Service.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You are aware that when requesting Services, whether by message, via Site or calling the call center of Bookit Cabs, standard messaging charges, data charges, voice charges, as applicable, of the Your and Our phone network service providers, will apply.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'CANCELLATION POLICY',
            style: TextStyle(fontSize: 23, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 10),
          Text(
            'You agree and acknowledge that You may cancel Your request for a Vehicle from a Driver at any point of time subject to a Cancellation Fee as explained below:',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'In Mini/Prime/Sedan/Suv/Rental Cancellation fee will be charged.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'If you cancel after 5 minutes after the cab is allotted.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'If the Driver is delayed by more than five (15) minutes to pick You, You will not be charged any Cancellation Fee.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'You shall be notified of the applicable Cancellation Fee in advance whenever you attempt to cancel a booking/service request. The notification shall be on the Application.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit Cabs shall provide a receipt of the Cancellation Fee.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'The Cancellation Fee shall be payable by You at the completion of Your subsequent Ride.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Bookit Cabs will be making calls and sending SMS through a third party platform.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
          const SizedBox(height: 10),
          Text(
            'Not with standing User\'s registration with National Do Not Call Registry (In Fully or Partly blocked category under National Customer Preference Register set up under Telecom Regulatory Authority of India), User hereby expresses his interest and accord its willful consent to receive communication (including commercial communication) in relation to Bookit Cabs Services. User further confirms that any communication, as mentioned herein above, shall not be construed as Unsolicited Commercial Communication under the TRAI guidelines and User has specifically opted to receive communication in this regard on the telephone number provided by the User.',
            textAlign: TextAlign.justify,
            style: TextStyle(fontSize: 20),
          ),
        ],
      ),
    );
  }
}
